apiVersion: apps/v1
kind: Deployment
metadata:
  name: mopidy-deployment
  labels:
    component: mopidy
spec:
  replicas: 3
  selector:
    matchLabels:
      component: mopidy
  template:
    metadata:
      labels:
        component: mopidy
    spec:
      containers:
      - name: mopidy
        image: ehudkaldor/mopidy
        ports:
        - containerPort: 6680
